services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    working_dir: /app
    stdin_open: true